### PR TITLE
feature/shadow color and bar visibility

### PR DESCRIPTION
**Pull request by georgiystrigun-lanars**

### CODE REVIEW

**Comment by adrianvintu** [comment]
I see the shadow is now set to
```
              shadow: BoxShadow(
                color: Color(0xFFEBEBEC),
                offset: Offset(0, -1.0),
                blurRadius: 5.0,
              ),
```

Can you make it so it looks `exactly` like in the old version, for example `animated_bottom_navigation_bar: ^0.3.2`?

It was a very think dark/grey line. You can test it by setting `backgroundColor: Theme.of(context).scaffoldBackgroundColor,` in the 0.3.2 version.

Second, hardcoding the color makes it not support dark theme. The old version supported light and dark theme without assigning the `shadow` property. Can you maybe use the shadow size and color from the old code, or from the Card or whatever widget it was using?

**Comment by vizhan-lanars** [comment]
Good point about light/dark theme.

**Comment by vizhan-lanars** [comment]
@adrianvintu 
Brought back elevation parameter at version 1.1.0

**Comment by adrianvintu** [comment]
Does the default shadow look `exactly` like the old one? I am too dumb to reproduce it manually...

It was a very think dark/grey line. You can test it by setting backgroundColor: Theme.of(context).scaffoldBackgroundColor, in the 0.3.2 version.

**Comment by georgiystrigun-lanars** [comment]
@adrianvintu yes, by default it has elevation = 8 (as it was in version 0.3.3). But also you can add custom shadow (as shown in the example), if you want.

**Comment by adrianvintu** [comment]
@georgiystrigun-lanars Tested v 1.1.0  in emulator, works as requested/as previous version. Has auto support for dark theme as well. I did not make any changes to code, except upgrading the version. Job well done! Thank you for your awesome work!

**Pull request merged**
